version: "3.5"
services:
  db:
    container_name: search-db
    image: mysql/mysql-server:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: +uR3s!UPyH7eHb0jUn9Ax5oS]4k
      MYSQL_DATABASE: search
      MYSQL_ROOT_HOST: '%'
    volumes: 
      - ./db_sql:/docker-entrypoint-initdb.d/:ro
    networks: 
      - database
  
  flask:
    container_name: flask
    build: ./
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      APP_DEBUG: "False"
      APP_PORT: 5000
      MYSQL_ROOT_PASS: +uR3s!UPyH7eHb0jUn9Ax5oS]4k
    depends_on:
      - db
    volumes: 
      - appdata:/var/www
    networks: 
      database:
      shared:
        ipv4_address: '10.1.0.110'

volumes: 
  appdata:
    driver: local

networks:
  database:
  shared:
    name: shared
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24