version: "3.5"
services:
  db:
    container_name: autoryzacja-db
    image: mysql/mysql-server:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6GX3uAqbMoWqx2l-iuDU47YmGkGh
      MYSQL_DATABASE: authentication
      MYSQL_ROOT_HOST: '%'
    volumes: 
      - ./db_sql:/docker-entrypoint-initdb.d/:ro
    networks: 
      - database
  
  flask:
    container_name: autoryzacja
    build: ./
    ports:
      - "6000:6000"
    environment:
      DB_HOST: db
      APP_DEBUG: "False"
      APP_PORT: 6000
    depends_on:
      - db
    volumes: 
      - appdata:/var/www
    networks: 
      database:
      shared:
        ipv4_address: '10.1.0.111'

volumes: 
  appdata:
    driver: local

networks:
  database:
  shared:
    name: shared
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24