version: "3.5"
services:
  db:
    container_name: library-B-db
    image: mysql/mysql-server:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ic3P3dZUvid9YdKAb-@P3JaDOp4s
      MYSQL_DATABASE: library
      MYSQL_ROOT_HOST: '%'
    volumes: 
      - ./db_sql:/docker-entrypoint-initdb.d/:ro
    networks: 
      - library
  
  web:
    container_name: libraryB
    build: ./
    ports:
      - "8002:8002"
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks: 
      library:
      shared:
        ipv4_address: '10.1.0.121'

networks:
  library:    
  shared:
    name: shared
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24